[package]
name = "hello_cargo"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
actix-web = "4"
actix-cors = "0.7"
jsonwebtoken = "9"
chrono = { version = "0.4", features = ["serde"] }
env_logger = "0.10"
log = "0.4"
serde_json = "1.0"
